---
title: "R ETL with AWS"
format: html
---

# Preface


# The Parts

## Access your AWS EC2
 
Open an SSH client. Locate your privat key used to launch the instance. Run the command if necessary, to ensure the key in no publically viewble.

On Linux, it is as easy as using the `chmod`:
```{bash eval = FALSE}
chmod 400 csgkp.pem
```

Connect to your instance using its public DNS. For example:

```{bash, eval = FALSE}
 ssh -i "csgkp.pem" user@[machine].[region].compute.amazonaws.com
```

```{bash, echo = FALSE, eval = FALSE}
 ssh -i "csgkp.pem" ec2-user@ec2-3-145-161-146.us-east-2.compute.amazonaws.com
```

Voila! You now have access to your server from the terminal.

## Setting up Git and Cloning Repo

First, install and set up Git:

```{bash, eval = FALSE}
sudo yum install git -y
```

Check the install:

```{bash eval = FALSE}
git --version
```

You will also need to set up the basic Git configuration:

```{bash eval = FALSE}
git config --global user.name "Your Username"
git config --global user.email "Your Email ID"
```

Check that it worked:

```{bash eval = FALSE}
git config --list
```

Now clone this repo into the server:

```{bash eval = FALSE}
sudo git clone https://github.com/cllghn/retl4aws 
```

## Install R

Enable the Extra Packages for Enterprise Linux (EPEL) repository:

```{bash eval = FALSE}
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm 
```

Enable the Optional repository:

```{bash eval = FALSE}
sudo subscription-manager repos --enable "rhel-*-optional-rpms"
```

Define the R version: 

```{bash eval = FALSE}
export R_VERSION=4.2.3
```

Download and install the desired version of R:

```{bash eval = FALSE}
curl -O https://cdn.rstudio.com/r/rhel-9/pkgs/R-${R_VERSION}-1-1.x86_64.rpm
sudo dnf install R-${R_VERSION}-1-1.x86_64.rpm
```

Make sure it all worked according to plan:

```{bash eval = FALSE}
/opt/R/${R_VERSION}/bin/R --version
```

Ensure that R is available on the default `PATH` variable by creating symbolic links to the version you installed:

```{bash eval = FALSE}
sudo ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/R
sudo ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/Rscript
```

## Set up Shiny Server

Before installing Shiny Server you must have R installed. Also, install the Shiny R package:

```{bash eval = FALSE}
sudo su - \
    -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""
```

Download and install the Shiny Server:

```{bash eval = FALSE}
sudo yum install wget

wget https://download3.rstudio.org/centos7/x86_64/shiny-server-1.5.20.1002-x86_64.rpm

sudo yum install --nogpgcheck shiny-server-1.5.20.1002-x86_64.rpm
```

Start it up:

```{bash eval = FALSE}
sudo systemctl start shiny-server
```

The configuration lives here:

```{bash eval=FALSE}
vim ../etc/shiny-server/shiny-server.conf
```

Check that is runs on the correct port (`3838`) and the location (`/srv/shiny-server`). **DON'T TOUCH A THING**.

Move the cloned app to the correct place on the server:

```{bash eval = FALSE}
mv /retl4aws/inst/simple_app ../srv/shiny-server/
```

For this to run, you will need all packages in the global file:


```{bash eval = FALSE}
sudo su - \
    -c "R -e \"install.packages(c('shinythemes', 'RSQLite', 'igraph', 'visNetwork', 'dplyr', 'dbplyr', 'stringr'), repos='http://cran.rstudio.com/')\""
```


## Set up RStudio Server

# Assembling the Pieces


# Parting Thoughts

